<?xml version="1.0" encoding="utf-8"?><Database Name="Classwork - May 23" Class="Classwork___May_23DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=&quot;Classwork - May 23&quot;;Integrated Security=True" SettingsObjectName="Classwork___May_23.Data.Properties.Settings" SettingsPropertyName="Classwork___May_23ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Candidates" Member="Candidates">
    <Type Name="Candidate">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="Status" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>